/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UiIcons {
  UiIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_3 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets_yes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smoke_yes = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_delivery = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alcohol_yes = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_yes = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData luggage_yes = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets_no = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groupbrand = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__1_ = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_4 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grouptrip = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluent_contact_card_group_48_filledexperience = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groupnumber = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groupmodel = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_5 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruble_fill0 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
